//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedGenreReportDetail
    {
        public int borrowedGenreReportId { get; set; }
        public int genreId { get; set; }
        public int NumberOfBorrowings { get; set; }
    
        public virtual BorrowedGenreReport BorrowedGenreReport { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
