//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowingCard()
        {
            this.BookReturnCards = new HashSet<BookReturnCard>();
        }
    
        public string id { get; set; }
        public string readerCardId { get; set; }
        public System.DateTime borrowingDate { get; set; }
        public System.DateTime dueDate { get; set; }
        public string employeeId { get; set; }
        public string bookInfoId { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReturnCard> BookReturnCards { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReaderCard ReaderCard { get; set; }
    }
}
