//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayReturnBookReportDetail
    {
        public int delayReturnBookReportId { get; set; }
        public string borrowingReturnCardId { get; set; }
        public int numberOfDelayReturn { get; set; }
    
        public virtual Borrowing_ReturnCard Borrowing_ReturnCard { get; set; }
        public virtual DelayReturnBookReport DelayReturnBookReport { get; set; }
    }
}
