//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> startingDate { get; set; }
        public Nullable<int> roleId { get; set; }
        public bool isDeleted { get; set; }
        public string Email { get; set; }
    }
}
