//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineReceipt
    {
        public string id { get; set; }
        public int amount { get; set; }
        public System.DateTime createdAt { get; set; }
        public string employeeId { get; set; }
        public string readerCardId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ReaderCard ReaderCard { get; set; }
    }
}
