//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportReceipt()
        {
            this.ImportReceiptDetails = new HashSet<ImportReceiptDetail>();
        }
    
        public string id { get; set; }
        public string supplier { get; set; }
        public int totalPrice { get; set; }
        public System.DateTime createdAt { get; set; }
        public string employeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportReceiptDetail> ImportReceiptDetails { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
