//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalHistory
    {
        public int id { get; set; }
        public string readerId { get; set; }
        public System.DateTime renewalDate { get; set; }
        public System.DateTime endDate { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual ReaderCard ReaderCard { get; set; }
    }
}
